# Generated by Django 5.2 on 2025-04-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_player_1', models.PositiveIntegerField(default=0)),
                ('score_player_2', models.PositiveIntegerField(default=0)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En attente', 'En Attente'), ('Acceptée', 'Acceptee'), ('Refusée', 'Refusee'), ('En cours', 'En Cours'), ('Terminée', 'Termine'), ('Annulée', 'Annulee')], default='En cours', max_length=10)),
                ('ball_position', models.JSONField(blank=True, default=dict, null=True)),
                ('paddle_position', models.JSONField(blank=True, default=dict, null=True)),
                ('ball_dx', models.IntegerField(default=1)),
                ('ball_dy', models.IntegerField(default=0)),
                ('ball_speed', models.FloatField(default=4)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('canvas_width', models.PositiveIntegerField(default=800)),
                ('canvas_height', models.PositiveIntegerField(default=400)),
                ('paddle_width', models.PositiveIntegerField(default=10)),
                ('paddle_height', models.PositiveIntegerField(default=80)),
                ('ball_radius', models.PositiveIntegerField(default=10)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='shared_models.match')),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player_1', to='shared_models.player')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player_2', to='shared_models.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='shared_models.player')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rounds', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('max_score_per_round', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('status', models.CharField(choices=[('En attente', 'En Attente'), ('Acceptée', 'Acceptee'), ('Refusée', 'Refusee'), ('En cours', 'En Cours'), ('Terminée', 'Termine'), ('Annulée', 'Annulee')], default='En attente', max_length=10)),
                ('match_type', models.CharField(choices=[('IA', 'Ia'), ('Normal', 'Normal'), ('Tournois', 'Tournament')], default='Normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='shared_models.player')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='shared_models.player')),
            ],
        ),
    ]
