# Generated by Django 5.2 on 2025-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ball_radius',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='canvas_height',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='game',
            name='canvas_width',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='game',
            name='paddle_height',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='paddle_width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
