# Generated by Django 5.2 on 2025-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_game_ball_radius_alter_game_canvas_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='canvas_height',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
