# Generated by Django 5.2 on 2025-05-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_game_canvas_height'),
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory', models.PositiveIntegerField(default=0)),
                ('defeat', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winrate', to='shared_models.player')),
            ],
        ),
    ]
