# Generated by Django 5.2 on 2025-04-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='shared_models_player',
        ),
    ]
