# Generated by Django 5.2 on 2025-04-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_alter_player_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='dbz_public_shared_models_player',
        ),
    ]
