# Generated by Django 5.2 on 2025-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_alter_player_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='dbz_public_shared_models_block',
        ),
        migrations.AlterModelTable(
            name='friendship',
            table='dbz_public_shared_models_friendship',
        ),
    ]
