# Generated by Django 5.2 on 2025-04-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_alter_block_table_alter_friendship_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='dbz_public_shared_models_match',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='dbz_public_shared_models_tournament',
        ),
    ]
