# Generated by Django 5.1.7 on 2025-04-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='private_code',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_number',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='max_score_per_round',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='match',
            name='number_of_rounds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_score_per_round',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_rounds',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_tournament', to='shared_models.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_tournament', to='shared_models.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_tournament', to='shared_models.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_tournament', to='shared_models.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player_1', to='shared_models.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player_2', to='shared_models.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('En attente', 'En Attente'), ('Acceptée', 'Acceptee'), ('Refusée', 'Refusee'), ('En cours', 'En Cours'), ('Terminée', 'Termine'), ('Annulée', 'Annulee')], default='En cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='shared_models.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('IA', 'Ia'), ('Normal', 'Normal'), ('Tournois', 'Tournament')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='shared_models.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En Cours'), ('Terminée', 'Termine')], default='Ouvert', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='shared_models.player'),
        ),
    ]
