# Generated by Django 5.1.7 on 2025-05-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_remove_match_private_code_remove_match_round_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='defeat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='victory',
        ),
    ]
