# Generated by Django 5.1.7 on 2025-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_remove_player_defeat_remove_player_victory'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
    ]
