# Generated by Django 5.1.7 on 2025-05-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_match_is_treated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_treated',
        ),
    ]
